version: '3'
services:
  sunshine:
    build: .
    container_name: sunshine
    restart: unless-stopped
    volumes:
      - ./config:/config
#    volumes:
#      - <path to data>:/config
#    environment:
#      - PUID=<uid>
#      - PGID=<gid>
#      - TZ=<timezone>
    ports:
      - "47984-47990:47984-47990/tcp"
      - "48010:48010"
      - "47998-48000:47998-48000/udp"
